import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";


import { useState, useEffect } from "react";

const FailureTransaction: NextPage = () => {
  const [accessToken, setAccessToken] = useState("");


  return (
    <div className={styles.container}>
      <Head>
        <title>OpenFabric</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
      </Head>

      <div className="container mt-2">
        <h4 className="mb-3">
          <strong>FailureTransaction</strong>
        </h4>
     
      </div>
    </div>
  );
};

export default FailureTransaction;
